---
creds:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: nxapi
  use_ssl: yes
  validate_certs: no
  port: 8443

creds_napalm:
  hostname: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  dev_os: "nxos"
  optional_args: { "port": 8443 }

ntp1: "10.1.1.1"
ntp2: "10.1.1.2"

ntp_baseline:
  - "10.1.1.1"
  - "10.1.1.2"
