---
- name: New VLANs on EOS and Validation
  hosts: pynet-sw7
  gather_facts: False
  vars:
    vlan_list:
       - { vlan_id: "500", name: "blue500" }
       - { vlan_id: "501", name: "blue501" }
       - { vlan_id: "502", name: "blue502" }
       - { vlan_id: "503", name: "blue503" }
       - { vlan_id: "504", name: "blue504" }
 
    default_vlan:
       - { vlan_id: "1", name: "default" }

    approved_vlans: "{{ vlan_list }} + {{ default_vlan }}"

  tasks:
    - name: Create New VLANs
      eos_config:
        provider: "{{ creds_eapi }}"
        lines:
          - "vlan {{ item.vlan_id }} name {{ item.name }}"
      with_items: "{{ vlan_list }}"
      tags: create_vlan

    - name: Check out the Configured VLANs
      eos_command:
        provider: "{{ creds_eapi }}"
        commands: show vlan
      tags: sh_vlan
      register: sh_vlan

    - name: Set Facts - Current configured VLAN IDs on the Switch
      set_fact:
        conf_vl_ids: "{{ sh_vlan.stdout_lines[0].vlans.keys() }}"

    - name: Display the configured VLAN IDs on the Switch
      debug:
        var: conf_vl_ids

    - name: Extract the Approved VLAN IDs
      set_fact:
        approved_ids: "{{ approved_vlans | map(attribute='vlan_id') | list }}"    

    - name: Display the Approved VLAN IDs
      debug:
        var: approved_ids

    - name: Check out VLAN Differences - Configured vs Approved
      set_fact:
        vlan_diff: "{{ conf_vl_ids | difference(approved_ids) }}"

    - name: Print out VLAN Differences
      debug:
        var: vlan_diff
      when: vlan_diff

    - name: Configured VLANs complies with the Approved VLANs 
      debug:
        msg: VLANs - OK (All configured VLANs are approved.)
      when: not vlan_diff

    - name: Unapproved VLANs configured on the switch
      debug:
        var: vlan_diff
      when: vlan_diff

    - name: Remove VLAN Differences
      eos_config:
        provider: "{{ creds_eapi }}"
        lines:
          - "no vlan {{ item }}"
      with_items: "{{ vlan_diff }}"
      tags: delete_vlan
      when: vlan_diff
