---
- name: Verify BGP Configs
  hosts: pynet-sw5:pynet-rtr1:pynet-sw6
  gather_facts: False
  tasks:
    - name: Verify BGP
      napalm_get_facts:
        provider: "{{ creds_napalm }}"
        filter: bgp_neighbors

    - name: Display the BGP Peers
      debug:
        msg: "{{ item.key }}"
      with_dict: "{{ napalm_bgp_neighbors.global.peers }}"

    - name: Set BGP Peers to a list
      set_fact:
        current_peers: "{{ current_peers | default([]) + [ item.key ] }}"
      with_dict: "{{ napalm_bgp_neighbors.global.peers }}"

    - name: Display Current BGP Peer List
      debug:
        msg: "{{ current_peers }}"
    
    - name: Set Intended BGP Peers
      set_fact:
        intended_peers: "{{ intended_peers | default([]) + [ item.peer_ip ] }}"
      with_items: "{{ bgp_peers }}"
## Alternatively, the above list can be formed as below
#    - name: Set Intended BGP Peers
#      set_fact:
#        intended_peers: "{{ bgp_peers | map(attribute='peer_ip') | list }}"

    - name: Display the intended BGP Peers List
      debug: 
        msg: "{{ intended_peers }}"

    - name: Verify - Compare BGP Neighbors
      assert:
        that: 
          - "{{ intended_peers | symmetric_difference(current_peers) | list }} == []"
        msg: "Intended and Current BGP Peer configurations differ!"
