---
- name: BGP and NTP
  hosts: localhost
  gather_facts: False
  vars:
    bgp_peers:
      peer1: 10.220.88.32
      peer2: 10.220.88.33
      peer3: 10.220.88.38
    ntp_servers:
      - ntp server 1.1.1.1
      - ntp server 2.2.2.2
      - ntp server 3.3.3.3

  tasks:
    - name: Print out the BGP Peers
      debug:
        var: bgp_peers
      tags: print_bgp

    - name: Print out the NTP Servers
      debug:
        msg: "{{ ntp_servers }}"
      tags: print_ntp
     
    - name: NTP server config delete
      debug:
        msg: "no {{ item }}"
      with_items: "{{ ntp_servers }}"  
