---
- name: OSPF on IOS Router
  hosts: pynet-rtr1
  gather_facts: False
  tasks: 
    - name: Configure OSPF
      ios_config:
        provider: "{{ creds_core_ssh }}"
        parents: ["router ospf 42"]
        lines:
          - network 10.220.88.0 0.0.0.255 area 0
        match: line
      notify: write_mem

  handlers:
    - name: write_mem
      ios_command:
        provider: "{{ creds_core_ssh }}"
        commands: write mem
      changed_when: True
      tags: wr_mem

- name: Create EOS Loopbacks & OSPF
  hosts: pynet-sw8
  gather_facts: False
  tasks:
    - name: Create EOS Loopbacks Template
      template:
        src: "{{ inventory_hostname }}-loopback.j2"
        dest: "CFGS/{{ inventory_hostname }}/1-interfaces.txt"
      tags: gen_loop

    - name: Create the OSPF Template
      template:
        src: "{{ inventory_hostname }}-ospf.j2"
        dest: "CFGS/{{inventory_hostname }}/2-ospf.txt"
      tags: gen_ospf

    - name: Generate the assembled template
      assemble:
        src: "CFGS/{{ inventory_hostname }}/"
        dest: "CFGS/{{ inventory_hostname }}.txt"
      tags: assemble_temps

    - name: Install EOS Loopbacks & OSPF Configs
      napalm_install_config:
        provider: "{{ creds_napalm }}"
        config_file: "CFGS/{{ inventory_hostname }}.txt"
        commit_changes: True
        replace_config: False
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
      tags: install_conf
      

