---
- name: Configure Arista Switchports
  hosts: pynet-sw6
  gather_facts: False
  tasks:
   # - name: Verify Connectivity (Ansible Core)
   #   eos_facts:
   #     provider: "{{ creds_core_eapi }}"

    - name: Verify Connectivity (NAPALM)
      napalm_get_facts:
        provider: "{{ creds_napalm }}"

    - name: Generate VLAN Configs
      template:
        src: vlans.j2
        dest: "CFGS/{{ inventory_hostname }}-vlans.txt"
      tags: gen_conf

    - name: Configure VLANs
      napalm_install_config:
        provider: "{{ creds_napalm }}"
        config_file: "CFGS/{{ inventory_hostname }}-vlans.txt"
        commit_changes: False
        replace_config: False
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
