---
- name: Generate config template
  hosts: cisco:nxos:arista
  gather_facts: False
  tasks:
    - name: Generate the Global configs for the devices
      template:
        src: ex1a_template.j2
        dest: "./CFGS/{{ inventory_hostname }}-global.txt"
      tags: 
        - gen_config
        - ios_push
        - nxos_push
        - eos_push

- name: Push IOS Global configs
  hosts: cisco
  gather_facts: False
  tasks:
    - name: Push IOS Config
      ios_config:
        provider: "{{ creds_ssh }}"
        src: "./CFGS/{{ inventory_hostname }}-global.txt"
      tags: ios_push

- name: Push NXOS Global configs
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Push NXOS Config
      nxos_config:
        provider: "{{ creds_ssh }}"
        src: "./CFGS/{{ inventory_hostname }}-global.txt"
      tags: nxos_push

- name: Push EOS Global configs
  hosts: arista
  gather_facts: False
  tasks:
    - name: Push EOS Config
      eos_config:
        provider: "{{ creds_ssh }}"
        src: "./CFGS/{{ inventory_hostname }}-global.txt"
      tags: eos_push
