---
- name: Generate config template
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Generate the BGP Configs
      template:
        src: ex2a_template.j2
        dest: "./CFGS/{{ inventory_hostname }}-bgp.txt"
      tags: gen_config

    - name: Push config to NXOS Switches
      napalm_install_config:
        provider: "{{ creds_napalm }}"
        config_file: "./CFGS/{{ inventory_hostname }}-bgp.txt"
        commit_changes: True
        replace_config: False
        diff_file: "./DIFFS/{{ inventory_hostname }}.txt"
      tags: push_nxos

    - name: Wait for 10 secs
      pause:
        seconds: 10

    - name: Verify IP Connectivity
      nxos_command:
        provider: "{{ creds_ssh }}"
        commands: "ping6 {{ bgp_int.peer_ip }}"
      tags: ping
      register: output

    - name: Evaluate the Ping Result
      set_fact:
        ping_reply: "{{ output.stdout[0].split(',')[-2].lstrip().split()[0] }}" 
      tags: ping

    - name: Display Ping Output
      debug:
        var: ping_reply
      tags: ping

    - name: Check out IPV6 BGP Session
      napalm_get_facts:
        provider: "{{ creds_napalm }}"
        filter: "bgp_neighbors"
      tags: bgp

    - name: Display BGP Neighbors
      debug:
        var: napalm_bgp_neighbors
      tags: bgp

    - name: Get the IPv6 BGP Session State
      set_fact:
        session_state: "{{ napalm_bgp_neighbors['global']['peers'][bgp_int.peer_ip]['is_up'] }}"
      tags: bgp

    - name: Print the Session State
      debug:
        var: session_state
      tags: bgp

    - name: Verify the IPV6 Connectivity & BGP Session State
      assert:
        that: 
          - ping_reply|int >= 1
          - session_state == true
        msg: "Session with {{ bgp_int.peer_ip }} is DOWN!"
      tags: bgp

