---
- name: Configuration templating using include statememnt
  hosts: localhost
  gather_facts: False
  tasks: 
    - name: Generate Configuration files
      template: 
        src: branch_office_ex1.j2
        dest: "./CFGS/{{ item.hostname }}.txt"
      with_items:
        - {hostname: pynet-rtr1, default_gateway: 10.10.10.1}
        - {hostname: pynet-rtr2, default_gateway: 10.10.20.1}
