---
creds_ssh:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"

snmp_contact: "snmp-admin@twb-tech.com"
snmp_location: "Atlanta"

global_config: # Domain, name-servers and ntp servers variables are taken from group_vars/all.yml file
  - "ip domain name {{ default_domain }}"
  - "ip name-server {{ name_server1 }}"
  - "ip name-server {{ name_server2 }}"
  - "ntp server {{ ntp1 }}"
  - "ntp server {{ ntp2 }}"

snmp_config: 
  - "snmp-server contact {{ snmp_contact }}"
  - "snmp-server location {{ snmp_location }}"
