---
- name: IOS Example
  hosts: cisco
  vars:
    creds: 
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - ios_facts:
        provider: "{{ creds }}"
      tags: facts_only

    - debug:
        var: ansible_net_model, ansible_net_image

    - ios_command:
        provider: "{{ creds }}"
        commands: show ip int brief
      tags: int_brief
      register: output

    - debug:
        msg: "{{ output['stdout_lines'][0][5] }}"
        # var: output['stdout_lines'][0]
