---
- name: With Testing
  hosts: local
  vars:
    my_devices:
      device1:
        ip_addr: 10.10.10.1
        device_type: cisco_ios
      device2:
        ip_addr: 10.10.20.1
        device_type: juniper_srx
      device3:
        ip_addr: 10.10.30.1
        device_type: arista_eos
  tasks: 
    - name: Test with dictionary
      debug: 
        msg: "{{ item.value.ip_addr }}"
      with_dict: "{{ my_devices }}"
