---
- name: NAPALM Get Info
  hosts: cisco
  tasks: 
    - name: LLDP Neighbors
      napalm_get_facts:
        provider: "{{ creds }}"
        filter: "lldp_neighbors"
      tags: lldp
    - name: Print LLDP Neighbors
      debug: 
        var: napalm_lldp_neighbors
