---
- name: NAPALM Validation
  hosts: pynet-sw8:pynet-rtr1
  tasks:
    - name: Napalm Validate
      napalm_validate:
        provider: "{{ creds }}"
        validation_file: "{{ validate_file }}" 
