---
- hosts: local
  vars:
    var1: hello
    var2: world
    my_dict:
      key1: aaa
      key2: bbb
      key3: ccc
    my_list: 
      - apple
      - orange
      - pear
      - mango
      - fig
      - strawberry
      - orange
      - apple
    my_list2:
      - orange
      - 3
      - 77
      - Arista
    device: Cisco
  
  tasks:
    - debug:
        msg: "{{ my_dict | to_yaml }}"  # Convert the dict to a YAML construct (A Jinja2 filter)

    - debug:
        msg: "{{ my_dict | to_nice_yaml }}"  # Convert the dict to a nicer looking YAML
   
