---
- name: Napalm Filter
  hosts: cisco
  vars:
    creds_napalm:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      dev_os: ios

  tasks:
    - name: NAPALM Get Arp table
      napalm_get_facts:
        provider: "{{ creds_napalm }}"
        filter: "arp_table"

    - name: Retrieve IP addresses as a list from ARP table
      debug:
        msg: "{{ napalm_arp_table | map(attribute='ip') | list }}"
      tags: arp

    - name: Retrieve IP:MAC as a dict
      set_fact:
        my_dict: "{{ my_dict|default({}) | combine( {item.ip: item.mac} ) }}"
      with_items: "{{ napalm_arp_table }}"

    - name: Print the New ARP Table
      debug:
        var: my_dict
