---
platform: ios
name_server1: 8.8.8.8
name_server2: 8.8.4.4

default_domain: bogus1.com

ntp1: 130.126.24.24
ntp2: 152.2.21.1

creds_ssh:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  timeout: 60

creds_napalm:
  hostname: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  dev_os: "ios"

