---
provider_ssh:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: cli
  timeout: 60
 
provider_nxapi:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: nxapi
  use_ssl: yes
  validate_certs: no
  port: 8443

vlans_common:
  - vlan_id: 301
    admin_state: up
    name: blue
  - vlan_id: 302
    admin_state: up
    name: red
  - vlan_id: 303
    admin_state: up
    name: green

vlans: "{{ vlans_common }} + {{ vlans_unique|default([]) }}"
